url: https://kylesezhi.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Interly Language Services
email: interlylanguageservices@gmail.com
description: "Personalized translation and copy-editing for academics and professionals. English, Japanese, and Spanish."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Danya Ramírez
  pic: 1
  position: English, Spanish, Japanese
  social:
    - title: linkedin
      url: #

- name: Kyle Bedell
  pic: 2
  position: English, Spanish, Japanese
  social:
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
